version: '3.8'

services:
  backend:
    build:
      context: ./FisioterapiaBack
      dockerfile: Presentation/Dockerfile
    ports:
      - "5223:5223"
    environment:
      - ASPNETCORE_URLS=http://+:5223
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped

  frontend:
    build:
      context: ./Fisioterapia
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
